package(default_visibility = ["//visibility:public"])

load("//renode:renode.bzl", "renode_test")

renode_test(
    name = "nxp-k64f-test",
    robot = "NXP-K64F.robot",
    binary = "nxp_k64f--zephyr_basic_uart.elf"
)
