load(":robot.bzl", "renode_test")

renode_test(
    name = "nxp-k64f-test",
    robot = "NXP-K64F.robot",
    binary = "nxp_k64f--zephyr_basic_uart.elf-s_618844-2d588c6899efaae76a7a27136fd8cff667bbcb6f"
)
