stages:
  - test

.common_triggers: &common_triggers
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
      - $CI_PIPELINE_SOURCE == "merge_request"
variables:
  BAZELISK_URL: https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64

.install_bazelisk: &install_bazelisk |-
  apt-get -qqy update > /dev/null && \
  apt-get -qqy --no-install-recommends install ca-certificates python3 build-essential clang git file zip wget && \
  wget -nv "$BAZELISK_URL" -O /usr/local/bin/bazelisk && \
  chmod +x /usr/local/bin/bazelisk

.examples_artifacts: &examples_artifacts
  after_script:
    - mkdir artifacts
    - cp -LR examples/*/bazel-testlogs/* artifacts
  artifacts:
      when:
        always
      paths:
        - artifacts

.default_bazel_version: &default_bazel_version
  variables:
    USE_BAZEL_VERSION: 7.4.1

test_examples:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: test
  <<: *common_triggers
  <<: *default_bazel_version
  before_script:
    - *install_bazelisk
    - apt -y install git automake cmake autoconf libtool g++ coreutils policykit-1
  script:
    - for file in examples/*/test_example.sh; do
    - (cd $(dirname "$file"); ./$(basename "$file"))
    - done
  <<: *examples_artifacts
