stages:
  - test

.common_triggers: &common_triggers
  only:
    variables:
      - $CI_COMMIT_REF_NAME == "master"
      - $CI_PIPELINE_SOURCE == "merge_request"
variables:
  BAZELISK_URL: https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64

.install_bazelisk: &install_bazelisk |-
  apt-get -qqy update > /dev/null && \
  apt-get -qqy --no-install-recommends install ca-certificates python3 build-essential clang git file zip wget && \
  wget -nv "$BAZELISK_URL" -O /usr/local/bin/bazelisk && \
  chmod +x /usr/local/bin/bazelisk

.examples_artifacts: &examples_artifacts
  after_script:
    - mkdir artifacts
    - cp -LR examples/*/bazel-testlogs/* artifacts
  artifacts:
      when:
        always
      paths:
        - artifacts

test_examples:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: test
  <<: *common_triggers
  variables:
    MIN_SIM_VCD_SIZE: 10000
  before_script:
    - *install_bazelisk
    - apt -y install git automake cmake autoconf libtool g++ coreutils policykit-1
  script:
    - pushd examples/verilator-cosimulation
    - bazelisk test //:all --nozip_undeclared_test_outputs
    - test $(du bazel-testlogs/dma/test.outputs/sim.vcd | cut -f1) -gt $MIN_SIM_VCD_SIZE
    - popd
    - pushd examples/renode-interactive
    - bazelisk run //:all | tee test.log
    - grep "TEST OK" test.log
    - popd
    - pushd examples/cortex-r52
    - bazelisk test //:all
    - ls bazel-testlogs/*/test.outputs/outputs.zip
    - popd
    - pushd examples/failing-test
    - "! bazelisk test //:all | tee test.log || exit 1"
    - ls bazel-testlogs/*/test.outputs/outputs.zip
    - grep -E "//:success-test +PASSED" test.log
    - grep -E "//:failing-test +FAILED" test.log
    - popd
    - pushd examples/local-renode
    - git clone --no-progress https://github.com/renode/renode.git
    - pushd renode
    - ./build.sh --net
    - popd
    - bazelisk test //:all
    - popd

  <<: *examples_artifacts
