load(
    "@rules_dotnet//dotnet:defs.bzl",
    "csharp_library",
)

package(default_visibility = ["//visibility:public"])

csharp_library(
    name = "Migrant",
    srcs = [
       "Migrant/AssemblyInfo.cs",
       "Migrant/BultinSurrogates/ISurrogateRestorer.cs",
       "Migrant/BultinSurrogates/SurrogateForDictionary.cs",
       "Migrant/BultinSurrogates/SurrogateForHashSet.cs",
       "Migrant/BultinSurrogates/SurrogateForHashtable.cs",
       "Migrant/BultinSurrogates/SurrogateForISerializable.cs",
       "Migrant/BultinSurrogates/SurrogateForIXmlSerializable.cs",
       "Migrant/BultinSurrogates/SurrogateForReadOnlyCollection.cs",
       "Migrant/CollectionMetaToken.cs",
       "Migrant/ConstructorAttribute.cs",
       "Migrant/Consts.cs",
       "Migrant/Customization/Method.cs",
       "Migrant/Customization/ReferencePreservation.cs",
       "Migrant/Customization/Settings.cs",
       "Migrant/Customization/VersionToleranceLevel.cs",
       "Migrant/DeserializationResult.cs",
       "Migrant/Generators/CallPostSerializationHooksMethodGenerator.cs",
       "Migrant/Generators/CloneContentMethodGenerator.cs",
       "Migrant/Generators/CompletedGenerator.cs",
       "Migrant/Generators/CreateGenericSurrogateMethodGenerator.cs",
       "Migrant/Generators/CreateObjectGenerator.cs",
       "Migrant/Generators/DynamicMethodGenerator.cs",
       "Migrant/Generators/DynamicReadMethodGenerator.cs",
       "Migrant/Generators/DynamicWriteMethodGenerator.cs",
       "Migrant/Generators/GenerationContextBase.cs",
       "Migrant/Generators/GeneratorHelper.cs",
       "Migrant/Generators/HandleNewReferenceMethodGenerator.cs",
       "Migrant/Generators/ReaderGenerationContext.cs",
       "Migrant/Generators/ReadMethodGenerator.cs",
       "Migrant/Generators/SurrogateObjectIfNeededMethodGenerator.cs",
       "Migrant/Generators/TouchInlinedObjectGenerator.cs",
       "Migrant/Generators/WriteMethodGenerator.cs",
       "Migrant/Generators/WriteReferenceMethodGenerator.cs",
       "Migrant/Generators/WriterGenerationContext.cs",
       "Migrant/Helpers.cs",
       "Migrant/Hooks/LatePostDeserializationAttribute.cs",
       "Migrant/Hooks/LatePostSerializationAttribute.cs",
       "Migrant/Hooks/PostDeserializationAttribute.cs",
       "Migrant/Hooks/PostSerializationAttribute.cs",
       "Migrant/Hooks/PreSerializationAttribute.cs",
       "Migrant/ISpeciallySerializable.cs",
       "Migrant/ObjectIdentifier.cs",
       "Migrant/ObjectIdentifierContext.cs",
       "Migrant/ObjectReader.cs",
       "Migrant/ObjectWriter.cs",
       "Migrant/PrimitiveReader.cs",
       "Migrant/PrimitiveWriter.cs",
       "Migrant/SerializationType.cs",
       "Migrant/Serializer.cs",
       "Migrant/TransientAttribute.cs",
       "Migrant/TypeOrGenericTypeArgument.cs",
       "Migrant/Utilities/AutoResizingList.cs",
       "Migrant/Utilities/DynamicMethodProvider.cs",
       "Migrant/Utilities/IdentifiedElementsDictionary.cs",
       "Migrant/Utilities/IdentifiedElementsList.cs",
       "Migrant/Utilities/IIdentifiedElement.cs",
       "Migrant/Utilities/OneToManyMap.cs",
       "Migrant/Utilities/OneToOneMap.cs",
       "Migrant/Utilities/PeekableStream.cs",
       "Migrant/Utilities/SwapList.cs",
       "Migrant/Utilities/TypeProvider.cs",
       "Migrant/Utilities/Variable.cs",
       "Migrant/VersionTolerance/ArrayDescriptor.cs",
       "Migrant/VersionTolerance/AssemblyDescriptor.cs",
       "Migrant/VersionTolerance/FieldDescriptor.cs",
       "Migrant/VersionTolerance/FieldInfoOrEntryToOmit.cs",
       "Migrant/VersionTolerance/MethodDescriptor.cs",
       "Migrant/VersionTolerance/ModuleDescriptor.cs",
       "Migrant/VersionTolerance/StampHelpers.cs",
       "Migrant/VersionTolerance/TypeDescriptor.cs",
       "Migrant/VersionTolerance/TypeFullDescriptor.cs",
       "Migrant/VersionTolerance/TypeSimpleDescriptor.cs",
       "Migrant/VersionTolerance/VersionToleranceException.cs",
    ],
    internals_visible_to = ["lib_migrant"],
    target_frameworks = ["net6.0"],
    targeting_packs = [
        "@rules_dotnet_nuget_packages//microsoft.netcore.app.ref",
    ],
    deps = [],
    defines = ["NET"],
)

