load("@rules_dotnet//dotnet:defs.bzl", "import_dll")

package(default_visibility = ["//visibility:public"])

import_dll(
    name = "LuceneNet",
    dll = "@renode_sources//:LuceneNet",
)

import_dll(
    name = "IronPython",
    dll = "@renode_sources//:IronPython",
)

import_dll(
    name = "IronPythonStdLib",
    dll = "@renode_sources//:IronPythonStdLib",
)

import_dll(
    name = "IronPythonModules",
    dll = "@renode_sources//:IronPythonModules",
)

import_dll(
    name = "MicrosoftScripting",
    dll = "@renode_sources//:MicrosoftScripting",
)

import_dll(
    name = "LZ4",
    dll = "@renode_sources//:LZ4",
)

import_dll(
    name = "MonoCecil",
    dll = "@renode_sources//:MonoCecil",
)

import_dll(
    name = "MonoLinqExpressions",
    dll = "@renode_sources//:MonoLinqExpressions",
)

import_dll(
    name = "MonoTextTemplating",
    dll = "@renode_sources//:MonoTextTemplating",
)

import_dll(
    name = "Dynamitey",
    dll = "@renode_sources//:Dynamitey",
)

import_dll(
    name = "Nini",
    dll = "@renode_sources//:Nini",
)

import_dll(
    name = "BitMiracleLibJpegNet",
    dll = "@renode_sources//:BitMiracleLibJpegNet",
)

import_dll(
    name = "Sprache",
    dll = "@renode_sources//:Sprache",
)

import_dll(
    name = "CookComputingXmlRpcV2",
    dll = "@renode_sources//:CookComputingXmlRpcV2",
)

import_dll(
    name = "FlatBuffers",
    dll = "@renode_sources//:FlatBuffers",
)

import_dll(
    name = "protobuf-net",
    dll = "@renode_sources//:protobuf-net",
)

import_dll(
    name = "MicrosoftDynamic",
    dll = "@renode_sources//:MicrosoftDynamic",
)
