load("//toolchain_renode/Infrastructure/Emulator/Cores/tlib/tcg:generic_tcg.bzl", "tcg_library")

tcg_library(
    architecture = "i386",
    target_word_size = "32",
    target_insn_start_extra_words = "1",
    endianess = "le"
)
