load(
    "@rules_dotnet//dotnet:defs.bzl",
    "csharp_library",
)

package(default_visibility = ["//visibility:public"])

csharp_library(
    name = "ELFSharp",
    srcs = [
     "ELFSharp/AssemblyInfo.cs",
     "ELFSharp/ELF/Class.cs",
     "ELFSharp/ELF/Consts.cs",
     "ELFSharp/ELF/ELF.cs",
     "ELFSharp/ELF/ELFReader.cs",
     "ELFSharp/ELF/Endianess.cs",
     "ELFSharp/ELF/FileType.cs",
     "ELFSharp/ELF/IELF.cs",
     "ELFSharp/ELF/Machine.cs",
     "ELFSharp/ELF/Sections/INoteSection.cs",
     "ELFSharp/ELF/Sections/IProgBitsSection.cs",
     "ELFSharp/ELF/Sections/ISection.cs",
     "ELFSharp/ELF/Sections/IStringTable.cs",
     "ELFSharp/ELF/Sections/ISymbolEntry.cs",
     "ELFSharp/ELF/Sections/ISymbolTable.cs",
     "ELFSharp/ELF/Sections/NoteData.cs",
     "ELFSharp/ELF/Sections/NoteSection.cs",
     "ELFSharp/ELF/Sections/ProgBitsSection.cs",
     "ELFSharp/ELF/Sections/Section.cs",
     "ELFSharp/ELF/Sections/SectionFlags.cs",
     "ELFSharp/ELF/Sections/SectionHeader.cs",
     "ELFSharp/ELF/Sections/SectionType.cs",
     "ELFSharp/ELF/Sections/SpecialSectionIndex.cs",
     "ELFSharp/ELF/Sections/SpecialSectionType.cs",
     "ELFSharp/ELF/Sections/StringTable.cs",
     "ELFSharp/ELF/Sections/SymbolBinding.cs",
     "ELFSharp/ELF/Sections/SymbolEntry.cs",
     "ELFSharp/ELF/Sections/SymbolTable.cs",
     "ELFSharp/ELF/Sections/SymbolType.cs",
     "ELFSharp/ELF/Segments/ISegment.cs",
     "ELFSharp/ELF/Segments/Segment.cs",
     "ELFSharp/ELF/Segments/SegmentFlags.cs",
     "ELFSharp/ELF/Segments/SegmentType.cs",
     "ELFSharp/ELF/Utilities.cs",
     "ELFSharp/MachO/Command.cs",
     "ELFSharp/MachO/CommandType.cs",
     "ELFSharp/MachO/FileType.cs",
     "ELFSharp/MachO/Machine.cs",
     "ELFSharp/MachO/MachO.cs",
     "ELFSharp/MachO/MachOReader.cs",
     "ELFSharp/MachO/MachOResult.cs",
     "ELFSharp/MachO/Symbol.cs",
     "ELFSharp/MachO/SymbolTable.cs",
     "ELFSharp/MiscUtil/BigEndianBitConverter.cs",
     "ELFSharp/MiscUtil/EndianBinaryReader.cs",
     "ELFSharp/MiscUtil/EndianBinaryWriter.cs",
     "ELFSharp/MiscUtil/EndianBitConverter.cs",
     "ELFSharp/MiscUtil/Endianness.cs",
     "ELFSharp/MiscUtil/LittleEndianBitConverter.cs",
     "ELFSharp/MiscUtil/NonClosingStreamWrapper.cs",
     "ELFSharp/MiscUtil/Streams.cs",
     "ELFSharp/PE/ImageExportDirectory.cs",
     "ELFSharp/PE/ImageFileHeader.cs",
     "ELFSharp/PE/ImageSectionHeader.cs",
     "ELFSharp/PE/NamesTable.cs",
     "ELFSharp/PE/PE.cs",
     "ELFSharp/PE/PEReader.cs",
     "ELFSharp/UImage/Architecture.cs",
     "ELFSharp/UImage/CompressionType.cs",
     "ELFSharp/UImage/ImageDataResult.cs",
     "ELFSharp/UImage/ImageType.cs",
     "ELFSharp/UImage/OS.cs",
     "ELFSharp/UImage/UImage.cs",
     "ELFSharp/UImage/UImageReader.cs",
     "ELFSharp/UImage/UImageResult.cs",
    ],
    internals_visible_to = ["lib_elfsharp"],
    target_frameworks = ["net6.0"],
    targeting_packs = [
        "@rules_dotnet_nuget_packages//microsoft.netcore.app.ref",
    ],
    deps = [],
    defines = ["NET"],
)
