load("@rules_dotnet//dotnet:defs.bzl", "import_dll")

package(default_visibility = ["//visibility:public"])

import_dll(
    name = "lucene",
    dll = "libraries/Lucene.Net.dll",
)

import_dll(
    name = "IronPython",
    dll = "libraries/IronPython.dll",
)

import_dll(
    name = "IronPythonStdLib",
    dll = "libraries/IronPython.StdLib.dll",
)

import_dll(
    name = "IronPythonModules",
    dll = "libraries/IronPython.Modules.dll",
)

import_dll(
    name = "MicrosoftScripting",
    dll = "libraries/Microsoft.Scripting.dll",
)

import_dll(
    name = "LZ4",
    dll = "libraries/LZ4.dll",
)

import_dll(
    name = "MonoCecil",
    dll = "libraries/Mono.Cecil.dll",
)

import_dll(
    name = "MonoLinqExpressions",
    dll = "libraries/Mono.Linq.Expressions.dll",
)

import_dll(
    name = "MonoTextTemplating",
    dll = "libraries/Mono.TextTemplating.dll",
)

import_dll(
    name = "Dynamitey",
    dll = "libraries/Dynamitey.dll",
)

import_dll(
    name = "Nini",
    dll = "libraries/Nini.dll",
)

import_dll(
    name = "BitMiracleLibJpegNet",
    dll = "libraries/BitMiracle.LibJpeg.NET.dll",
)

import_dll(
    name = "Sprache",
    dll = "libraries/Sprache.dll",
)

import_dll(
    name = "CookComputingXmlRpcV2",
    dll = "libraries/CookComputing.XmlRpcV2.dll",
)

import_dll(
    name = "FlatBuffers",
    dll = "libraries/FlatBuffers.dll",
)

import_dll(
    name = "protobuf-net",
    dll = "libraries/protobuf-net.dll",
)

import_dll(
    name = "MicrosoftDynamic",
    dll = "libraries/Microsoft.Dynamic.dll",
)

filegroup(
    name = "robot-style",
    srcs = ["styles/robot.css"],
)
