name: Renode Bazel Rules test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      RENODE_VERSION: "1.12.0"
      RENODE_NIGHTLY_COMMIT: "20210415git39ecc7c"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Renode
        run: |
          sudo apt -qqy update && sudo apt -qqy install gtk-sharp2

          if [[ -z "${RENODE_NIGHTLY_COMMIT}" ]]; then
            export URL=https://github.com/renode/renode/releases/download/v${RENODE_VERSION}/renode_${RENODE_VERSION}_amd64.deb
          else
            export URL=https://dl.antmicro.com/projects/renode/builds/renode_${RENODE_VERSION}+${RENODE_NIGHTLY_COMMIT}_amd64.deb
          fi

          wget -O /tmp/renode.deb $URL 
          sudo dpkg -i /tmp/renode.deb
          sudo pip install -r /opt/renode/tests/requirements.txt
          mkdir -p ~/.config/renode

      - name: Run example test
        run: |
          bazel test //examples/nxp-k64f:nxp-k64f-test

      - name: Upload Bazel artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: renode-bazel-artifacts
          path: bazel-testlogs*/**/*
