name: Renode Bazel Rules test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Temporary workaround
        run: mkdir -p ~/.config/renode

      - name: Run example test
        run: |
          bazel test //examples/nxp-k64f:nxp-k64f-test

      - name: Upload Bazel artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: renode-bazel-artifacts
          path: bazel-testlogs*/**/*
