name: Renode Bazel Rules test

on:
  - push
  - workflow_dispatch

jobs:
  test_examples:
    name: Test examples
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run example tests
        env:
          USE_BAZEL_VERSION: 7.4.1
        run: |
          pushd examples/cortex-r52
          bazelisk test //:all
          ls bazel-testlogs/*/test.outputs/outputs.zip
          popd
          pushd examples/failing-test
          ! bazelisk test //:all > test.log || exit 1
          ls bazel-testlogs/*/test.outputs/outputs.zip
          grep -E "//:success-test +PASSED" test.log
          grep -E "//:failing-test +FAILED" test.log
          popd

      - name: Upload Bazel artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: renode-bazel-artifacts
          path: examples/*/bazel-testlogs*/**/*
