name: Renode Bazel Rules test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build toolchain
        run: |
          bazel build @toolchain_renode//...

      - name: Display renode help
        run: |
          bazel-out/k8-fastbuild-ST-19c30ace4401/bin/external/toolchain_renode/bazelout/net6.0/Renode.dll.sh.runfiles/__main__/external/toolchain_renode/bazelout/net6.0/Renode --help

      - name: Run renode
        run: |
          bazel-out/k8-fastbuild-ST-19c30ace4401/bin/external/toolchain_renode/bazelout/net6.0/Renode.dll.sh.runfiles/__main__/external/toolchain_renode/bazelout/net6.0/Renode

      - name: Run test
        run: |
          bazel test //examples/nxp-k64f:nxp-k64f-test

      - name: Upload Bazel artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: renode-bazel-artifacts
          path: bazel-testlogs*/**/*
