name: Renode Bazel Rules test

on:
  - push
  - workflow_dispatch

jobs:
  test_examples:
    name: Test examples
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run example tests
        env:
          USE_BAZEL_VERSION: 7.4.1
        run: |
          for file in examples/*/test_example.sh; do
          (cd $(dirname "$file"); ./$(basename "$file"))
          done

      - name: Upload Bazel artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: renode-bazel-artifacts
          path: examples/*/bazel-testlogs*/**/*
