name: Renode Bazel Rules test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      RENODE_VERSION: "1.12.0"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Renode
        run: |
          sudo apt -qqy update && sudo apt -qqy install gtk-sharp2
          wget -O /tmp/renode.deb https://github.com/renode/renode/releases/download/v${{ env.RENODE_VERSION }}/renode_${{ env.RENODE_VERSION }}_amd64.deb
          sudo dpkg -i /tmp/renode.deb

      - name: Run example test
        run: |
          bazel test //examples/nxp-k64f:nxp-k64f-test

      - name: Upload Bazel artifacts
        uses: actions/upload-artifact@v2
        with:
          name: renode-bazel-artifacts
          path: bazel-testlogs*/**/*
