name: Renode Bazel Rules test

on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run example test
        run: |
          cd examples/cortex-r52
          bazel test //:cortex-r52-test

      - name: Upload Bazel artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: renode-bazel-artifacts
          path: examples/*/bazel-testlogs*/**/*
